server:
  port: 9001
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8671/eureka/,http://localhost:8672/eureka/
      defaultZone: http://cloudnote-eureka-8671:8671/eureka/
spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
#    host: 127.0.0.1
    host: myRedis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 1000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  application:
    name: noteServices
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloud_note?useSSL=false&amp;serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://47.107.128.33:3306/cloud_note?useSSL=false&amp;serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

    username: root
    password: mysql.
  servlet:
    multipart:
      max-file-size: 30Mb
#logback日志
logback:
  enableConsoleLogWhenNotInDev: true
  logFileDir: /acc-Log

#mybatis相关配置
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
  #打印sql语句
logging:
  level:
    com.cloudnote.note.dao.mapper: debug