spring:
  application:
    name: zuul
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
#    host: 127.0.0.1
    host: myRedis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 1000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

eureka:
  instance:
    instance-id: zuul
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://localhost:8671/eureka/,http://localhost:8672/eureka/
      defaultZone: http://cloudnote-eureka-8671:8671/eureka/

server:
  port: 8800
zuul:
  routes:
    sso-api:
      path: /sso/**
      serviceId: sso
    note-api:
      path: /noteServices/**
      serviceId: noteServices
    bin-api:
      path: /binServices/**
      serviceId: binServices
    notebook-api:
      path: /notebookServices/**
      serviceId: notebookServices
    usr-api:
      path: /userServices/**
      serviceId: userServices
    main-api:
      path: /mainService/**
      serviceId: EUREKA-CLIENT-WEB
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
  ignored-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials,H-APP-Id,Token,APPToken
ribbon:
  ReadTimeout: 6000000