spring:
  application:
    name: zuul
eureka:
  instance:
    instance-id: cloudnote.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/,http://localhost:8672/eureka/

server:
  port: 8800

zuul:
  routes:
    sso-api:
      path: /sso/**
      serviceId: SSO
    note-api:
      path: /noteServices/**
      serviceId: note
    bin-api:
      path: /binServices/**
      serviceId: binServices
    notebook-api:
      path: /notebookServices/**
      serviceId: notebookServices
    usr-api:
      path: /userServices/**
      serviceId: userServices
    main-api:
      path: /mainService/**
      serviceId: EUREKA-CLIENT-WEB