spring:
  application:
    name: zuul
eureka:
  instance:
    instance-id: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/,http://localhost:8672/eureka/

server:
  port: 8800
zuul:
  routes:
    sso-api:
      path: /sso/**
      serviceId: sso
    note-api:
      path: /noteServices/**
      serviceId: noteServices
    bin-api:
      path: /binServices/**
      serviceId: binServices
    notebook-api:
      path: /notebookServices/**
      serviceId: notebookServices
    usr-api:
      path: /userServices/**
      serviceId: userServices
    main-api:
      path: /mainService/**
      serviceId: EUREKA-CLIENT-WEB
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
  ignored-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials,H-APP-Id,Token,APPToken
ribbon:
  ReadTimeout: 6000000